name: Release

on:
    release:
        types: [created]

jobs:
    publish-docker-image:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: splunkdlt/dlt-connect-libs/actions/build-publish-container@main
              with:
                  publish-type: release
                  ghcr-org: splunkdlt
                  ghcr-release-name: ethlogger
                  ghcr-pre-release-name: ethlogger-pre
                  ghcr-user: ${{ secrets.GHCR_USER }}
                  ghcr-pat: ${{ secrets.GHCR_PAT }}
                  github-token: ${{ secrets.RELEASE_GH_TOKEN }}
